AWSTemplateFormatVersion: '2010-09-09'
Description: A simple, version-controlled web server

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 key pair

Resources:
  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      SecurityGroups:
        - !Ref WebServerSG
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
      UserData:
        Fn::Base64: |
          #!/bin/bash
          dnf install -y nginx
          systemctl enable nginx
          systemctl start nginx
          chown -R ec2-user:ec2-user /usr/share/nginx/html

Outputs:
  PublicIP:
    Value: !GetAtt WebServer.PublicIp